{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "my-app-monitoring.fullname" . }}-frontend-network-policy
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.targetPort }} 
{{- end }}
