# k8s/full-monitoring/prometheus-rules.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  kubernetes-alerts.yaml: |
    groups:
    - name: kubernetes.rules
      rules:
      - alert: KubePodCrashLooping
        expr: sum(increase(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace=~"whisper-namespace|monitoring"}[5m])) by (pod, namespace, container) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Pod {{ $labels.pod }} in {{ $labels.namespace }} is crashlooping
          description: "Container {{ $labels.container }} in pod {{ $labels.pod }} (namespace {{ $labels.namespace }}) has restarted multiple times."

      - alert: KubeDeploymentReplicasMismatch
        expr: kube_deployment_spec_replicas{job="kube-state-metrics",namespace=~"whisper-namespace|monitoring"} != kube_deployment_status_replicas_available{job="kube-state-metrics",namespace=~"whisper-namespace|monitoring"}
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Deployment replicas mismatch ({{ $labels.deployment }} in {{ $labels.namespace }})
          description: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has a replica mismatch. Desired: {{ $value }} Available: {{ $labels.available_replicas }}"

    - name: node.rules
      rules:
      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Node Exporter is down (instance {{ $labels.instance }})
          description: "Node Exporter on {{ $labels.instance }} is not reachable. Metrics from this node are not being collected."

      - alert: NodeHighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle", job="node-exporter"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on node (instance {{ $labels.instance }})
          description: "Node {{ $labels.instance }} has CPU usage above 80% for 5 minutes."
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules # Note: This name is used in prometheus.yaml
  namespace: monitoring
data:
  app-alerts.yaml: |
    groups:
    - name: application-alerts
      rules:
      - alert: BackendHighRequestLatency
        expr: histogram_quantile(0.99, rate(whisper_backend_request_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Backend request latency too high ({{ $value }}s)"
          description: "The 99th percentile request latency for the backend is above 1 second for 5 minutes."

      - alert: BackendModelLoadFailed
        expr: whisper_model_load_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Whisper Model Failed to Load"
          description: "The Whisper AI model failed to load on the backend pod."

      - alert: FrontendBackendCommunicationError
        expr: sum(rate(whisper_frontend_backend_api_calls_total{job="whisper-apps", http_status_code=~"5xx|4xx"}[5m])) by (app_kubernetes_name) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Frontend failed to communicate with backend"
          description: "Frontend is experiencing errors when calling backend API."

    - name: kubernetes-resource-alerts
      rules:
      - alert: NodeHighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Node CPU usage is high ({{ $value }}%)"
          description: "Node {{ $labels.instance }} has CPU usage above 80% for 5 minutes."

      - alert: PodRestartsTooFrequent
        expr: changes(kube_pod_container_status_restarts_total{namespace="whisper-namespace", container=~"whisper|frontend-container"}[15m]) > 2
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Pod restarting frequently"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 2 times in 15 minutes."