apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-monitoring.fullname" . }}-{{ .Values.frontend.name }}-service
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
    app: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      name: http
  type: {{ .Values.frontend.service.type }}
  {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
  nodePort: {{ .Values.frontend.service.nodePort }}
  {{- end }}
