{{- if .Values.backend.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pvc.name }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.pvc.size }}
  {{- if .Values.backend.pvc.storageClassName }}
  storageClassName: {{ .Values.backend.pvc.storageClassName }}
  {{- end }}
{{- end }}
