apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-pvc
  labels:
    app: whisper-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi