apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-cache-pvc
  namespace: whisper-namespace
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi