apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-backend-deployment
  labels:
    app: whisper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-backend
  template:
    metadata:
      labels:
        app: whisper-backend
    spec:
      volumes:
        - name: audio-input-storage
          hostPath:
            path: /mnt/audio-data
            type: DirectoryOrCreate
      containers:
        - name: whisper-backend-container
          image: your-dockerhub-username/whisper-inference:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "16Gi"
              cpu: "1000m"
            limits:
              memory: "18Gi"
              cpu: "2000m"
          volumeMounts:
            - name: audio-input-storage
              mountPath: /app/received_audio
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3