apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-backend-deployment
  namespace: whisper-namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: audio-storage
          hostPath:
            path: /mnt/audio-data
            type: DirectoryOrCreate
        - name: whisper-cache-volume # Added this volume
          persistentVolumeClaim:
            claimName: whisper-model-cache-pvc
      containers:
        - name: whisper
          image: vishalg2022/whisper:2
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: audio-storage # Corrected name from 'audio-input'
              mountPath: /tmp
            - name: whisper-cache-volume # Added this volume mount
              mountPath: /root/.cache/whisper
        