apiVersion: v1
kind: Service
metadata:
  name: whisper-backend-service
  namespace: whisper-namespace
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP