apiVersion: v1
kind: Service
metadata:
  name: whisper-backend-service
  labels:
    app: whisper-backend
spec:
  selector:
    app: whisper-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP