apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: whisper-namespace
  labels:
    app: frontend
    metrics: "true"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer