apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoring.prometheus.name }}
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.monitoring.prometheus.name }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - replicasets
  - deployments
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.monitoring.prometheus.name }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.monitoring.prometheus.name }}
  namespace: {{ .Values.monitoringNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.monitoring.prometheus.name }}
  apiGroup: rbac.authorization.k8s.io
