apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app-monitoring.fullname" . }}-grafana-config
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    http_port = {{ .Values.monitoring.grafana.service.targetPort }}
    [auth.anonymous]
    enabled = false
    [security]
    admin_user = {{ .Values.monitoring.grafana.adminUser }}
    admin_password = {{ .Values.monitoring.grafana.adminPassword }}
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ include "my-app-monitoring.fullname" . }}-prometheus-service.{{ .Values.monitoringNamespace }}:{{ .Values.monitoring.prometheus.service.targetPort }}
      access: proxy
      isDefault: true
      editable: true
