apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-monitoring.fullname" . }}-grafana-service
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
    app: {{ .Values.monitoring.grafana.name }}
spec:
  selector:
    app: {{ .Values.monitoring.grafana.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: {{ .Values.monitoring.grafana.service.targetPort }}
      name: http
  type: {{ .Values.monitoring.grafana.service.type }}
  {{- if and (eq .Values.monitoring.grafana.service.type "NodePort") .Values.monitoring.grafana.service.nodePort }}
  nodePort: {{ .Values.monitoring.grafana.service.nodePort }}
  {{- end }}
