apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-monitoring.fullname" . }}-node-exporter-service
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    {{- include "my-app-monitoring.labels" . | nindent 4 }}
    app: {{ .Values.monitoring.nodeExporter.name }}
spec:
  selector:
    app: {{ .Values.monitoring.nodeExporter.name }}
  ports:
  - name: http
    port: 9100
    targetPort: 9100
  type: ClusterIP